apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: ai-ml-ops-cluster
spec:
  rayVersion: "2.7.0"
  enableInTreeAutoscaling: true
  headGroupSpec:
    rayStartParams:
      dashboard-host: "0.0.0.0"
    template:
      spec:
        containers:
          - name: ray-head
            image: ai-ml-ops-serve:latest
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 6379
              - containerPort: 8265
              - containerPort: 10001
              - containerPort: 8000
            resources:
              limits:
                cpu: "2"
                memory: "4Gi"
              requests:
                cpu: "1"
                memory: "2Gi"
  workerGroupSpecs:
    - replicas: 1
      minReplicas: 1
      maxReplicas: 3
      groupName: worker
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-worker
              image: ai-ml-ops-serve:latest
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: "2"
                  memory: "4Gi"
                requests:
                  cpu: "1"
                  memory: "2Gi"
