services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.3.1
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri /mlruns
      --default-artifact-root /mlruns
    volumes:
      - ../mlruns:/mlruns
    ports:
      - "5000:5000"
